[workspace]
resolver = "2"
members = ["server/*", "common", "client/sochat_client_lib", "client/sochat-tau/src-tauri", "integration_tests"]
# exclude = ["client/sochat-tau/src-tauri"]

[profile.release]
strip = "debuginfo"
# codegen-units = 1
# lto = "fat"
# [profile.dev.package."*"]
# inherits = "release"
# opt-level = 3


[profile.dev.package.sqlx-macros]
opt-level = 1
