[workspace]
resolver = "2"
members = ["server", "common", "client_lib"]

[profile.release]
strip = "debuginfo"
# codegen-units = 1
# lto = "fat"
# [profile.dev.package."*"]
# inherits = "release"
# opt-level = 3


[profile.dev.package.sqlx-macros]
opt-level = 3