[workspace]
resolver = "2"
members = ["client_service", "client_frb", "server", "common", "client_service"]

[profile.release]
strip = "debuginfo"
# [profile.dev.package."*"]
# inherits = "release"
# opt-level = 3
