[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = { version = "0.7.4", features = ["ws"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
base64 = "0.21.7"
chrono = "0.4.33"
common = { version = "0.1.0", path = "../common" }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
log = "0.4.20"
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["json"] }
rustls = "0.22.2"
rustls-pemfile = "2.0.0"
serde = { version = "1.0.195", features = ["derive", "alloc", "rc"] }
serde_bytes = "0.11.14"
serde_json = { version = "1.0.111", features = ["alloc"] }
serde_with = { version = "3.5.1", features = ["base64", "chrono"] }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["full"] }
uuid = { version = "1.6.1", features = ["v7"] }

[dev-dependencies]
reqwest = "0.11.23"
