[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1"
axum = { version = "^0.7", features = ["ws"] }
axum-server = { version = "^0.6", features = ["tls-rustls"] }
base64 = "^0.22"
chrono = "^0.4"
common = { version = "0.1.0", path = "../common" }
ed25519-dalek = { version = "^2", features = ["rand_core"] }
futures-util = "^0.3"
itertools = "^0.12"
log = "^0.4"
once_cell = "^1.19"
serde = { version = "^1", features = ["derive", "alloc", "rc"] }
serde_json = { version = "^1", features = ["alloc"] }
serde_with = { version = "^3", features = ["base64", "chrono"] }
sqlx = { version = "^0.7", features = ["sqlite", "runtime-tokio"] }
thiserror = "^1.0"
tokio = { version = "^1", features = ["full"] }
tokio-stream = "^0.1"
uuid = { version = "^1.8", features = ["v7"] }
