// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `equals`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageId>>
abstract class MessageId implements RustOpaqueInterface, IdExt {
  bool equals({required MessageId other});

  PlatformInt64 get hashCode;

  String toString();

  @override
  bool operator ==(Object other) {
    if (this.runtimeType != other.runtimeType) {
      return false;
    }

    return this.equals(other: other as dynamic);
  }
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserId>>
abstract class UserId implements RustOpaqueInterface, IdExt {
  bool equals({required UserId other});

  PlatformInt64 get hashCode;

  String toString();

  @override
  bool operator ==(Object other) {
    if (this.runtimeType != other.runtimeType) {
      return false;
    }

    return this.equals(other: other as dynamic);
  }
}

abstract class IdExt {
  PlatformInt64 get hashCode;

  String toString();
}
