// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.39.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartMessageId>>
abstract class MessageId implements RustOpaqueInterface {
  bool equals({required MessageId other});

  PlatformInt64 get hashCode;

  String toString();

  @override
  bool operator ==(Object other) {
    // using runtimeType instead of is operator so that it's easier to write the macro
    if (other.runtimeType != this.runtimeType) {
      return false;
    }
    return this.equals(other: other as dynamic);
  }
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartUserId>>
abstract class UserId implements RustOpaqueInterface {
  bool equals({required UserId other});

  PlatformInt64 get hashCode;

  String toString();

  @override
  bool operator ==(Object other) {
    // using runtimeType instead of is operator so that it's easier to write the macro
    if (other.runtimeType != this.runtimeType) {
      return false;
    }
    return this.equals(other: other as dynamic);
  }
}
