[package]
name = "rust_lib_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0"
client_lib = { path = "../client_lib" }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread"] }
anyhow = "1.0.86"
